In [2]:
#Igual

igual= 2 ==3

In [3]:
import numpy as np
listaPes=[1000,950,870,1200]
arreglopes= np.array(listaPes).reshape(2,2)
print(arreglopes)
mascarLogica= np.logical_and(arreglopes>=1000, arreglopes<1500)#mascara logica entre y entre. compara entre toda la lista
print(mascarLogica)
print(arreglopes[mascarLogica])#Imprima los numero que cumplen la condicion

[[1000  950]
 [ 870 1200]]
[[ True False]
 [False  True]]
[1000 1200]


In [4]:
#Ejemplo

edades=[36, 27, 25,24,22]
print( edades[0]>edades[1] and edades [0]> edades [2]> edades [3]> edades [4])



True


## Conditional statements

In [5]:
area=50

if(area>=50):
    print("La casa es grande")
elif(area<50 and area>40):
    print("La casa es mediana")
else:
    print("La casa es pequeña")

La casa es grande


In [6]:
#Recorridos

nombre= "Carla"
switch(nombre): 
    case "andres": print("El nombre es andres");
            break;
    case "joy": print("El nombre es andres");
    


SyntaxError: invalid syntax (<ipython-input-6-26d9eaa4c5e5>, line 4)

## Loops

In [ ]:
#

error= 10

while error>0.1: #"coge el error y lo divide hasta que se cumpla la condicion"
    error= error/4
    print(error)

In [ ]:
offset=8
while offset!=0:
    print("Entrada al ciclo", offset)
    offset= offset-1
    print("Salida del ciclo", offset)

In [ ]:
farm=[1.73, 1.68, 1.71,1.89]
for valores in farm:
    print("Index {1}: {0}".format(farm.index(valores), valores ))#dudas
    valores= valores*2
    
    
farm=[1.73, 1.68, 1.71,1.89]
for valores in farm:
    print("Index", farm.index(valores), ":", valores)
    valores= valores*2

In [ ]:
#Recorrido-Iterar
ArregloFarm= np.array(farm)
for index, value in enumerate(ArregloFarm):
    if()
    print(index, value)

In [ ]:
weight= [74,72,78,80,90]
height= [180,190,200,150,195]
np_height= np.array(height)
np_weight= np.array(weight)
np_baseball= np.vstack((np_height, np_weight))
print(np_baseball)
#ierar sobre valores
prueba= np.nditer(np_baseball) #Todos los contenidos internos de la lista sin importar la posicion (la vuelve una lista una debajo de otra)
for index, valores in enumerate(prueba):
    print("index: {0} -- {1}".format(index, valores))

In [ ]:
#Iterar sobre fias. osea que imprima fila por fila
for index, rows in enumerate(np_baseball):
    print("index: {0} -- {1}".format(index, rows))

In [ ]:
#Iterar sobre columnas, IMPRIME POR COLUMNAS
for index, colums in enumerate(np_baseball.T):
 print("index: {0} -- {1}".format(index, colums))

In [ ]:
#Generar Numeros aleatorios. random funcion, rand el metodo


print(np.random.rand())#entre 0 y 1 siempre, 0 a 100%
print(np.random.rand(1,2)) #filas y columnas



In [ ]:
np.random.seed(1)#modifica el  numero de la semilla, fija el numero random
print(np.random.rand())

In [ ]:
np.random.seed(1)#modifica el  numero de la semilla, es un espejo del de arriba, ancla # aleatorios. siguen el mismo patron. para replicar modelos
print(np.random.rand())

In [ ]:
#Numeros aleatorios enteros
print(np.random.randint(1,10,10)) #No toca el 10, el 3 valor es la cantidad de numero que deseamos

for i in range(0,10): #un rango entre 0 y 10
    print(np.random.randint(1,10,10))
    
for i in range(0,10): #un rango entre 0 y 10
    print("\n",i)


In [ ]:
for index, value in enumerate(np.arange(0,10,1)): #un rango entre 0 y 10
    print("\n",value)


In [10]:
#dado 50 veces cual es el numero que sale mas veces


for i in range(1,7): #un rango entre 0 y 10
    print(np.random.randint(1,5,5))
#Arre


[4 2 4 4 2]
[1 1 1 3 4]
[3 3 4 2 2]
[1 3 3 3 1]
[3 2 2 4 2]
[2 3 1 4 3]
