# Numpy

In [2]:
#Nos permite crear arreglos, son un tipo de objeto que son optimizados para procesarce en grandes cantidades de datos
#Importar la libreria dentro de jupiter, le estamos diciendo que busque en el directorio


import numpy as np #Importar libreria "as" le colocamos un nombre a la libreria con la cual la podemos seguir llamando

a=[1,2,3]
b =["Nombre",False, 3.0, 4]

npCorrecto= np.ndarray(a) #De tipo lista a Numpy

print(npCorrecto)
print(type(npCorrecto)) #Verificar en que libreria esta


[[[0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>


In [3]:
exper= np.array(b)
print(exper[0]) 
print(type(exper[0])) #String numpy

Nombre
<class 'numpy.str_'>


In [4]:
#Una lista de listas

C=[[1,2,3],[4,5,6],[7,8,9]]
npCorrect2 = np.array(C) #De tipo lista a Numpy

print(c)
print (len(C))
print(npCorrect2)
print(npCorrect2.shape) #NUmero de columnas y filas

NameError: name 'c' is not defined

In [ ]:
exper= np.array(c)
print(npCorrect2[1][1]) #Ir a una ubicacion exacta del arreglo


npCorrect2[1,1]=15 #Modificar un dato en especifico
npCorrect2[2,2]=19 #Manera mas optima de modificar
print(npCorrect2) 
print(npCorrect2.size)#Cuantos elementos hay dentro de la matriz


In [ ]:
3d = [[[1,2,3],[1,2,3]]],[[-,-]]

In [ ]:
#Lista de una dimension

Lista1dimen=[1,2,3]
Lista2dimen= [[1,2,3],[4,5,6]]
Lista3dimen= [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]
np1dimen= np.array(Lista1dimen)
np2dimen= np.array(Lista2dimen)
np3dimen= np.array(Lista3dimen)

print(np1dimen, "\n---------")
print(np1dimen.shape, "\n---------")
print(np2dimen, "\n---------")
print(np2dimen.shape, "\n---------")
print(np3dimen, "\n---------")
print(np3dimen.shape, "\n---------")

In [33]:
array1 = np.arange(0,8,1) #Crear un bector posicion 10, hasta el 20 de 6 en 6
listaTest= range(8)
listaExtendida= np.array(listaTest.append(9))
#truncadaarray= array1[0:9]
#truncadaarray= array1.append(np.mean()) NO FUNCIONA
print(array1)
print(type(array1))
print(listaTest)
#lista = range(0,20, 2)#No funciona debe ser con Numpy
#print(lista)


print(array1.shape) #Cuanrtos elementos o filas tiene de una dimension



#Cambiar las dimensiones  de un bector que ya creamos
#nuevasDime= array1.reshape(3,3,3) #Lo pasa a 3 filas con 3 columnas, tiene que ser proporcional con el numero de elementos
nuevasDime= listaExtendida.reshape(3,3)
print(nuevasDime)



AttributeError: 'range' object has no attribute 'append'

In [37]:
Array2 = np.arange(0,9,1)
Array3 = np.linspace(0,10,9) #cuantas casillas quiere que imprima, divide 10 en 9

print(Array2)
print(Array3)

[0 1 2 3 4 5 6 7 8]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [46]:
#Funciones predeterminadas

valoresdeSeno= np.linspace(0, 2*np.pi,10)
print(valoresdeSeno, "\n----------" )
#Sacaer el seno de esos valores

seno=np.sin(valoresdeSeno)
print(seno)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531] 
----------
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [47]:
arreglo5= np.array([[1,2],[3,4]])
arreglo6= np.array([[4,3],[2,1]])

In [ ]:
A= arreglo5.dot(arreglo6)

B= arreglo6.dot(arreglo5)

In [49]:
#Sumas de matrices
print(arreglo5+arreglo6)
#resta de matrices
print(arreglo5-arreglo6)

#Elevacion punto a punto
print(arreglo5**2)




[[5 5]
 [5 5]]
[[-3 -1]
 [ 1  3]]
[[ 1  4]
 [ 9 16]]


In [60]:
#CONCATENAR MATRICES VERTICALMENTE

concaVertical1=np.vstack((A,B))
concaVertical2=np.concatenate((A,B), axis =0)#Axis son ejes, que las pegue por el eje x0
print(concaVertical1,"----------------------\n",concaVertical2 )


#CONCATENAR HORIZONTAL

concaVertical11=np.hstack((A,B))
concaVertical22=np.concatenate((A,B), axis =1)
print(concaVertical11,concaVertical22, "----------------------\n")

NameError: name 'A' is not defined

In [ ]:
aumentaDimensiones= np.dstack((A,B))
print(aumentaDimensiones)
