# Numpy

In [6]:
#Nos permite crear arreglos, son un tipo de objeto que son optimizados para procesarce en grandes cantidades de datos
#Importar la libreria dentro de jupiter, le estamos diciendo que busque en el directorio


import numpy as np #Importar libreria "as" le colocamos un nombre a la libreria con la cual la podemos seguir llamando

a=[1,2,3]
b =["Nombre",False, 3.0, 4]

npCorrecto= np.ndarray(a) #De tipo lista a Numpy

print(npCorrecto)
print(type(npCorrecto)) #Verificar en que libreria esta


[[[0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>


In [11]:
exper= np.array(b)
print(exper[0]) 
print(type(exper[0])) #String numpy

Nombre
<class 'numpy.str_'>


In [21]:
#Una lista de listas

C=[[1,2,3],[4,5,6],[7,8,9]]
npCorrect2 = np.array(C) #De tipo lista a Numpy

print(c)
print (len(C))
print(npCorrect2)
print(npCorrect2.shape) #NUmero de columnas y filas

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [30]:
exper= np.array(c)
print(npCorrect2[1][1]) #Ir a una ubicacion exacta del arreglo


npCorrect2[1,1]=15 #Modificar un dato en especifico
npCorrect2[2,2]=19 #Manera mas optima de modificar
print(npCorrect2) 
print(npCorrect2.size)#Cuantos elementos hay dentro de la matriz


15
[[ 1  2  3]
 [ 4 15  6]
 [ 7  8 19]]
9


In [ ]:
3d = [[[1,2,3],[1,2,3]]],[[-,-]]

In [47]:
#Lista de una dimension

Lista1dimen=[1,2,3]
Lista2dimen= [[1,2,3],[4,5,6]]
Lista3dimen= [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]
np1dimen= np.array(Lista1dimen)
np2dimen= np.array(Lista2dimen)
np3dimen= np.array(Lista3dimen)

print(np1dimen, "\n---------")
print(np1dimen.shape, "\n---------")
print(np2dimen, "\n---------")
print(np2dimen.shape, "\n---------")
print(np3dimen, "\n---------")
print(np3dimen.shape, "\n---------")

[1 2 3] 
---------
(3,) 
---------
[[1 2 3]
 [4 5 6]] 
---------
(2, 3) 
---------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]] 
---------
(1, 4, 3) 
---------
